# PLACEHOLDER — hand-written stand-in, not generated by build_agent.py.
# The API key used to bootstrap this project has no credit balance yet, so
# `python build_agent.py commit_message_agent` couldn't run. Once billing is
# sorted, re-run that command — it will overwrite this file with Claude's
# actual output from ../specs/commit_message_agent.md.

import os

import anthropic

MODEL = "claude-opus-5"

SYSTEM_PROMPT = """You write git commit messages. Given a diff, return a single \
line under 72 characters summarizing the change and, when inferable, why it was \
made. No body, no markdown, no trailing period."""


def generate_commit_message(diff: str) -> str:
    if not diff.strip():
        return "No changes to commit."

    client = anthropic.Anthropic()

    try:
        response = client.messages.create(
            model=MODEL,
            max_tokens=256,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": diff}],
        )
    except anthropic.APIStatusError as e:
        raise RuntimeError(f"API error: {e.message}") from e
    except anthropic.APIConnectionError as e:
        raise RuntimeError("Network error — check your connection.") from e

    return next((block.text for block in response.content if block.type == "text"), "").strip()
